# Generated by Django 6.0.2 on 2026-02-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_studentuser_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
