# Generated by Django 6.0.2 on 2026-02-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_remove_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
