# Generated by Django 6.0.2 on 2026-03-05 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_recruiter_company_recruiter_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='recruiter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.recruiter'),
            preserve_default=False,
        ),
    ]
